<?php
/**
 * Lightweight transient cache.
 *
 * @package AIO_Starter
 */

if (!defined('ABSPATH')) {
    exit;
}

add_action('template_redirect', 'aio_starter_cache_start', 0);
function aio_starter_cache_start() {
    $method = isset($_SERVER['REQUEST_METHOD']) ? strtoupper(sanitize_text_field(wp_unslash($_SERVER['REQUEST_METHOD']))) : 'GET';
    if (aio_starter_get_option('static_cache', '0') !== '1' || is_user_logged_in() || is_admin() || is_search() || is_404() || is_feed() || $method !== 'GET') {
        return;
    }

    if (is_singular() && comments_open()) {
        return;
    }

    $key = aio_starter_cache_key();
    $cached = get_transient($key);
    if (is_string($cached) && $cached !== '') {
        header('X-AIO-Starter-Cache: HIT');
        echo $cached; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Cached full HTML generated by WordPress.
        exit;
    }

    ob_start('aio_starter_cache_store');
}

function aio_starter_cache_store($html) {
    if (strlen($html) > 500 && false !== stripos($html, '</html>')) {
        set_transient(aio_starter_cache_key(), $html, HOUR_IN_SECONDS);
    }
    return $html;
}

function aio_starter_cache_key() {
    $uri = isset($_SERVER['REQUEST_URI']) ? sanitize_text_field(wp_unslash($_SERVER['REQUEST_URI'])) : '/';
    $version = (string) get_option('aio_starter_cache_version', '1');
    return 'aio_starter_cache_' . md5($version . '|' . $uri);
}

add_action('save_post', 'aio_starter_cache_purge');
add_action('comment_post', 'aio_starter_cache_purge');
add_action('edit_comment', 'aio_starter_cache_purge');
add_action('delete_comment', 'aio_starter_cache_purge');
add_action('trash_comment', 'aio_starter_cache_purge');
add_action('untrash_comment', 'aio_starter_cache_purge');
add_action('transition_comment_status', 'aio_starter_cache_purge');
add_action('switch_theme', 'aio_starter_cache_purge');
function aio_starter_cache_purge() {
    update_option('aio_starter_cache_version', str_replace(' ', '.', (string) microtime()), false);
}
